### ISSUE TITLE
Looking for SCI papers corresponding to HSI-Classification-GAN code

### ISSUE THREAD

**Issue by AlanMorningLight** [jaikanthjay46/HSI-Classification-GAN#1]
Thank you very much for your code. Do you have a Published SCI paper for this  HSI-Classification-GAN code? I'd like to learn. Thank you

**Comment by jaikanthjay46** [comment]
This is an implementation of this paper https://ieeexplore.ieee.org/document/8307247.

**Comment by AlanMorningLight** [comment]
Thank you very much. You are very selfless.

**Comment by Yuzikun-gu** [comment]
Thank you very much.It helps me a lot

**Comment by Yuzikun-gu** [comment]
what is patchify ?   I can not find it

**Comment by jaikanthjay46** [comment]
its a python package for splitting the images into patches of 64x64 pixels

**Comment by Yuzikun-gu** [comment]
Thanks for your answer,and I have another question: How many samples were taken as the training samples in the 3dgan_train.py? according to the paper, 200 samples were selected, but I cannot get the corresponding information in this code.

**Comment by jaikanthjay46** [comment]
That is actually varied in train test split and I remember them taking 10000 samples

**Comment by Yuzikun-gu** [comment]
why the shape of X_train is (21025,64,64,3)?  it is the whole data set?

**Comment by jaikanthjay46** [comment]
Yes, shit 3D gan didn’t have train test split, open a separate issue for that
